language: cpp
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - ./tests/tests --enable-gcov
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
