name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: QMAKE init
      run: qmake

    - name: MAKE start
      run: make

    - name: Run tests
      run: .tests/tests
