name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-default qt5-qmake

    - name: QMAKE init
      run: qmake

    - name: MAKE start
      run: make

    - name: Run tests
      run: .tests/tests
